// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dk.clanie.bitcoin.client.response;

import dk.clanie.bitcoin.client.response.BitcoindError;

privileged aspect BitcoindError_Roo_JavaBean {
    
    public Integer BitcoindError.getCode() {
        return this.code;
    }
    
    public String BitcoindError.getMessage() {
        return this.message;
    }
    
}
