// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dk.clanie.bitcoin.client.response;

import dk.clanie.bitcoin.client.response.GetWorkResult;

privileged aspect GetWorkResult_Roo_JavaBean {
    
    public String GetWorkResult.getData() {
        return this.data;
    }
    
    public String GetWorkResult.getTarget() {
        return this.target;
    }
    
}
