// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dk.clanie.bitcoin;

import dk.clanie.bitcoin.ScriptSig;

privileged aspect ScriptSig_Roo_JavaBean {
    
    public String ScriptSig.getAsm() {
        return this.asm;
    }
    
    public String ScriptSig.getHex() {
        return this.hex;
    }
    
}
