// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dk.clanie.bitcoin;

import dk.clanie.bitcoin.TransactionOutputRef;

privileged aspect TransactionOutputRef_Roo_JavaBean {
    
    public String TransactionOutputRef.getTxId() {
        return this.txId;
    }
    
    public Integer TransactionOutputRef.getVout() {
        return this.vout;
    }
    
}
